### Read in all collaborator files from OpenAlex, as generated by the python script
# NAs in the orcid column indicate that a named collaborator was either:
# 	1) not in the OpenAlex authors record or 
#	2) was in the OpenAlex authors record but did not have an orcid id listed there
fnames<-list.files(pattern="co_authors*")
coauthors<-do.call("rbind",lapply(fnames,read.csv,stringsAsFactors=FALSE))
head(coauthors)

#Some display_names will be non-unique and also valid
#Some display_names will be NA on some records but have an orcid on
# others
# Rough attempt to correct the latter. 
ncos<-by(coauthors$orcid,coauthors$display_name,unique)[which(lapply(by(coauthors$orcid,coauthors$display_name,unique),length)>1)]

for(i in 1:length(ncos)){
  if(length(ncos[i])>1){
    if(sum(is.na(ncos[i]))>0){
      x<-ncos[i][which(!is.na(ncos[i]))][[1]]
      nco.ind<-which(coauthors$display_name%in%names(ncos)[i])
      coauthors[nco.ind,"orcid"]<-x
    }
  }
}

#Add source authors (participants) to their collaborator lists
egos<-list()

for(i in 1:length(fnames)){
	gsub(".csv","",gsub("co_authors_","",rep(fnames[i],nrow(read.csv(fnames[i],stringsAsFactors = FALSE))))) -> egos[[i]]
}


coauthors$participant<-unlist(egos)
coauthors$collaborator<-gsub("https://orcid.org/","",coauthors$orcid)

#Add loops to ensure that all participants are self-collaborators
np<-length(unique(coauthors$participant))

author.loops<-as.data.frame(cbind(rep(NA,np),rep(NA,np),rep(NA,np),unique(coauthors$participant),unique(coauthors$participant)))
colnames(author.loops)<-colnames(coauthors)
coauthors<-rbind(coauthors,author.loops)
tail(coauthors)

#Subset to just the CERN OSF participants
coauthors.osf<-coauthors[which(coauthors$collaborator%in%coauthors$participant),]
head(coauthors.osf)
tail(coauthors.osf)

#Generate simple networks of these data
library(statnet)
coauthors.osf.net<-as.network(coauthors.osf[,4:5],loops=TRUE)
coauthors.osf.net

png("coauthors.net.png",bg="transparent",width=1000,height=1000)
plot(coauthors.osf.net,usearrows=FALSE,vertex.col="#FF500B",loop.steps=0,vertex.sides=200)
dev.off()

#network, dropping collaborators without ORCIDs

if(0){
	mmat<-matrix(0,length(unique(coauthors[,4])),length(unique(coauthors[,5])),dimnames = list(unique(coauthors[,4]),unique(coauthors[,5])))
	for(i in 1:nrow(coauthors)){
		if(!is.na(coauthors[i,5])){
			mmat[coauthors[i,4],coauthors[i,5]]<-1
		}
	}  
                  
	coauthors.net<-as.network(mmat,bipartite=TRUE)
	coauthors.net

	plot(coauthors.net,usearrows=FALSE,displayisolates=FALSE,loop.steps=0)
	savehistory("coauthors.test.R")
}